[project]
name = "2026sp-420-notavirus-exe"
version = "0.1.0"
description = "Feature extension for Scheduler"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "course-constraint-scheduler>=2.6.1",
    "pytest>=9.0.2",
]
